### ISSUE TITLE
Fixed Timestep for text rendering

### ISSUE THREAD

**Issue by onelson** [onelson/talkie#6]
Currently, the billboard display system reveals one glyph of the text *per tick* which means different computers may render the text at different speeds since the tick rate depends on how quickly the computer can process each tick. Faster computation means a higher frequency.

Ideally, all computers should see the text at the same rate.
The classic solution to this problem is to [Fix Your Timestep](https://gafferongames.com/post/fix_your_timestep/), which means tracking how much time (in the wallclock sense) has passed between each tick and skipping work until *enough time has passed*.

What will be required for us is to:

- Add a `Read<'s, Time>` to the billboard display system's `SystemData`.
- Use the read storage to gain access to the `Time` instance.
- Decide on a "glyphs per sec" or "glyphs per ms" rate (the **period**) and add a module constant to represent this.
- Add a field to the display system to track the "ongoing remainder" (ie an accumulator) for the time delta with each tick (more on this below).

In order to use the time delta between ticks to decide whether or not to reveal the next glyph, we'll have to something like the following with each tick.

- add the time delta to the accumulator
- get the [integer division] and [remainder] of the accumulator (by the **period**)
- reveal 1 glyph per division then set the accumulator to the value of the remainder 
- *repeat!*

> Example: if the period is *300ms*, the time delta is *450ms* and the accumulator is *100ms*, we would reveal 1 glyph and set the accumulator to *250ms*.

### Related Docs

- <https://doc.rust-lang.org/std/primitive.f32.html#examples-3>
- <https://doc.rust-lang.org/std/ops/trait.Rem.html?search=#examples-1>
- <https://book.amethyst.rs/stable/pong-tutorial/pong-tutorial-04.html#create-systems-to-make-the-ball-move>
- https://docs.amethyst.rs/stable/amethyst_core/timing/struct.Time.html

[integer division]: https://doc.rust-lang.org/std/primitive.f32.html#examples-3
[remainder]: https://doc.rust-lang.org/std/ops/trait.Rem.html?search=#examples-1

**Comment by rachelkelly** [comment]
I think I can get by with this.  I am trying to write something of my own first and ran across time, and now find that I will need to use `time::Instant`, a time marker that can be used with `time::Duration` and works well with milliseconds.  TY!  I will probably add more notes here as I go.
